<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>TarotDeckD_Lumox</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>TarotDeckD&amp;D</AssemblyName>
	<!-- Força a criação de um arquivo único -->
    <PublishSingleFile>true</PublishSingleFile>
    
    <!-- Embutir as DLLs nativas (coreclr.dll, etc) dentro do EXE -->
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    
    <!-- Define que o app rodará independente de ter o .NET instalado -->
    <SelfContained>true</SelfContained>
    
    <!-- Necessário para arquivo único -->
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    
    <!-- Impede a geração daquelas pastas de idiomas (cs, de, es, fr, etc.) -->
    <SatelliteResourceLanguages>pt-BR;en-US</SatelliteResourceLanguages>
  </PropertyGroup>

</Project>
